version: '3.4'
services:
  mtr-api:
    image: leakeymaina/mtrapi
    build: 
        context: .
        dockerfile: MTRAPI/Dockerfile
    environment:
      - DB_PW
    ports:
        - "80:80"
    depends_on:
      - mtr-db

  mtr-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        SA_PASSWORD: "${DB_PW}"
        ACCEPT_EULA: "Y"
    ports:
    - "1433:1433"

