SELECT [ETRID]
      ,[RegistrationDate]
      ,[Telephone]
      ,[TaxPayerID]
      ,[CurrentMonthSalesAmount]
      ,[CurrentMonthVATAmount]
      ,[CurrentYearSalesAmount]
      ,[CurrentYearVATAmount]
  FROM [MTR].[dbo].[ETRs]